# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
-   repo: local
    hooks:
    - id: nb-clean
      name: nb-clean
      description: "Clean Jupyter notebooks of outputs, metadata, and empty cells, with Git integration"
      entry: python
      require_serial: true
      language: system
      types_or: [jupyter]
      minimum_pre_commit_version: 2.9.2
      args: ["-m", "tox", "-qqq", "run", "-e", "nb-clean", "--", "clean", "--preserve-cell-metadata", "tags", "--"]
    - id: ruff
      name: ruff
      description: "Run 'ruff' for extremely fast Python linting"
      entry: tox -qqq run -e ruff -- check --force-exclude
      language: python
      types_or: [python, pyi, jupyter]
      require_serial: true
      additional_dependencies: []
      minimum_pre_commit_version: "2.9.2"
      args: ["--fix", "--exit-non-zero-on-fix"]
    - id: black
      name: black
      description: "Black: The uncompromising Python code formatter"
      minimum_pre_commit_version: 2.9.2
      require_serial: true
      types_or: [python, pyi, jupyter]
      entry: python
      language: system
      args: ["-m", "tox", "-qqq", "run", "-e", "black", "--"]
    - id: detect-azure-secrets-custom
      name: Detect Azure Secrets
      entry: python .github/scripts/detect_azure_secrets.py
      language: python
      types: [file]
